version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-slim-buster
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - restore_cache:
          key: 
            - v1-dependencies-{{ checksum "requirements/dev.txt" }}
            - v1-dependencies-
      - run: pip install -r requirements/dev.txt 
      - run:
          command: |
            flask db upgrate
            flask test
          environment:
            CONDUIT_SECRET: 'something-really-secret'
            FLASK_APP: /path/to/autoapp.py
            FLASK_DEBUG: 1
      
workflows:
  version: 2
  build-test-and-install:
    jobs:
      - build