version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: Ubuntu
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ''
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements/dev.txt" }}-{{ checksum "requirements/prod.txt" }}
            
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt 
      - run:
          command: |
            . venv/bin/activate
            flask db upgrade
            flask test
          environment:
            CONDUIT_SECRET: 'something-really-secret'
            FLASK_APP: autoapp.py
            FLASK_DEBUG: 1
            DATABASE_URL: postgresql://Ubuntu:somePwd@localhost:5432/postgres
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements/dev.txt" }}-{{ checksum "requirements/prod.txt" }}
          paths:
            - 'venv'
      
workflows:
  version: 2
  build-test-and-install:
    jobs:
      - build